name: meal_app
description: A meal prep planning app with Firebase Authentication.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  firebase_core: ^2.32.0
  firebase_auth: ^4.16.0
  google_sign_in: ^6.1.5
  cloud_firestore: ^4.17.5
  firebase_storage: ^11.7.5
  mobx: ^2.3.3
  flutter_mobx: ^2.0.6
  provider: ^6.0.5
  logger: ^2.2.0
  # Removed flutter_svg; using PNG background instead

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.11
  mobx_codegen: ^2.6.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
