import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/material.dart';

import 'app.dart';
import 'firebase_options.dart';

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();

  try {
    await Firebase.initializeApp(
      options: DefaultFirebaseOptions.currentPlatform,
    );
  } on FirebaseException catch (error) {
    throw Exception(
      'Failed to initialize Firebase. Double-check your configuration in '
      "lib/firebase_options.dart and make sure you've added the platform "
      'configuration files generated by the FlutterFire CLI.\n\n'
      'FirebaseException: ${error.message}',
    );
  }

  runApp(const MealPrepApp());
}
